### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
There are already a few submissions on reviews.llvm.org already for this. Closing.

**Comment by voddan** [comment]
What about migrating the python bindings to Python3? Surprisedly this is not addressed in this PR, but never the less.

Can we expect the official PIP package to be updated to Python3? To whom should I talk about it?

**Comment by SylvainCorlay** [comment]
@voddan I closed this PR since it was not submitted in the right channels and other patches were submitted addressing the same issue. I have some ongoing work to fix some outstanding "legacy-python" things.

**Comment by voddan** [comment]
@SylvainCorlay I have no objections to the closing of this issue.

However I wanted to ask you wether there is work going on to fix the python bindings (not the python parts on clang). As I see it, file https://github.com/llvm-mirror/clang/blob/master/bindings/python/clang/cindex.py is almost entirely python3, with an exception of few `print ""` and `raise Error, ""`.

So my questions are:
1) Is there any work in progress to fix those issues with python bindings?
2) Is fixing those things as simple as it looks?
3) Could I contribute fixing those issues ?
4) Where would I contribute it? Here on Github? Somewhere else?
5) When is it planed to update the official `clang` package on PIP?
6) Where would be appropriate to ask such questions in the future?

Thank you

**Comment by SylvainCorlay** [comment]
Just to avoid confusion: I am not a llvm developer. This was a drive-by pull request. The proper channel to submit patches is https://reviews.llvm.org

**Comment by voddan** [comment]
Ok, thank you for clarifying.

Could you please direct me about my other questions?

**Pull request closed without merging**
