### PR TITLE
fortran support

### PR DESCRIPTION
**Pull request by junghans**
There are patches to support f[lang](https://github.com/flang-compiler/flang) taken from [here](https://github.com/flang-compiler/clang).

### CODE REVIEW

**Comment by bfontaine** [comment]
> The place to submit patches is http://reviews.llvm.org/

**Comment by junghans** [comment]
https://reviews.llvm.org/D34097

**Comment by junghans** [comment]
Updated version at #33.

**Comment by junghans** [comment]
@hfinkel is taking care of https://reviews.llvm.org/D34097 now.

**Pull request closed without merging**
